SeoulBomo/SeoulBomo.FE

src/app/layout.tsx

- pretendard 적용했습니다
---
- localfont 적용
---
---
- 내용을 입력해주세요

feat: Pretendard Font 적용

---

src/components/main/CardFrame.tsx
src/components/main/PopularCard.tsx
tailwind.config.js

- popular card를 구현 후 cardFrame에 넣었습니다
- text는 hover시 underline을 주었고 overflow 시 ellipsis를 주었습니다 또한 7개의 데이터만 노출되도록 퍼블리싱 했습니다
---
- 없음

[Feat] Popular 카드 구현

---

src/app/page.tsx
src/components/main/CardFrame.tsx
src/components/main/NewsCard.tsx
src/components/main/PopularCard.tsx

- 복지 소식 카드를 구현했고 carousel 형태는 현재 오류로 인해 보류한 상태입니다 회색 칸에 이미지가 들어갈 예정입니다
---
- cardFrame의 w-screen h-screen으로 주어 임의로 정렬을 하였습니다
---
---
- 없음

[Feat] 복지 소식 카드 구현

---

src/app/layout.tsx
src/app/page.tsx
src/components/main/CalculateCard.tsx
src/components/main/CardFrame.tsx

- cardFrame 반응형 리팩토링
- header layout으로 이동
- CardFrame을 감싸는 전체 페이지에 style 추가
---
- cardFrame에서 직접 사이즈 준 것을 대부분 제거 한 후 padding으로 대체 flex가 반응하도록 설정
- flex-wrap 설정으로 줄어들었을 시 cardFrame에 따라 card 컴포넌트들이 정렬되어짐
- CardFrame을 감싸는 전체 페이지에 flex 등 style 추가
---
---
- 내용을 입력해주세요

[Refactor] cardFrame 반응형 리팩토링, header 이동, CardFrame Page div style 추가

---

src/components/information/InformationCard.tsx
src/components/information/InformationFrame.tsx

- Information 페이지를 구현했습니다 정책들을 나타내는 컴포넌트를 hover 했을 시 translate을 주어 오른쪽으로 움직이도록 만들었는데 버튼 색을 바꿀지 translate로 할지 논의가 필요할 것 같습니다
---
- InformationFrame이 전체적인 Information 페이지를 나타내고 흰색 카드는 Information Card를 통해 컴포넌트로 분리하였습니다 
- 또한 그리드를 주어 정렬시켰습니다
---    
---
- 내용을 입력해주세요

[Feat] Information 페이지 구현

---

src/components/SearchCard.tsx
src/components/filterSearch/FilterSearchFrame.tsx
src/components/information/InformationCard.tsx
src/components/information/InformationFrame.tsx
src/components/mainSearch/MainSearchFrame.tsx

- 통합 검색 결과 화면, 필터 검색 결과 화면 , 검색 결과 컴포넌트를 구현하였습니다 검색결과 컴포넌트 hover 시 shadow를 더 주었고 내용 더보기 또는 제목을 hover 할 시 underline을 설정했습니다 또한 information 페이지 css와 informationCard props 객체 형태로 받도록 변경했습니다
---
- 검색 결과 컴포넌트는 다른 페이지에서도 사용될 예정이므로 component 폴더에 넣었습니다
---
---
- 내용을 입력해주세요

[Feat] 통합 검색 결과 화면 및 필터 검색 결과 화면 구현

---

src/components/SearchCard.tsx
src/components/mapSearch/MapSearchFrame.tsx

- 지도 검색 결과 페이지 구현 및 Search Card 컴포넌트 크기 조정했습니다
- <img width="1253" alt="image" src="https://github.com/SeoulBomo/SeoulBomo.FE/assets/81469686/d9ebd826-99f0-4432-9345-66b6cdfc40b8">
---
---
---
- 내용을 입력해주세요

[Feat] 지도 검색 결과 페이지 구현

---

src/components/my/MypageFrame.tsx

- 마이페이지 구현하고 제목 hover시 underline 버튼 hover시 색 변경하였습니다
-
- 데이터 받아오는 부분은 추후 고칠 예정이라 map 함수나 더미데이터를 사용하지않았습니다
---
---
- 내용을 입력해주세요

[Feat] 마이페이지 구현

---

src/app/about-us/page.tsx
src/app/layout.tsx
src/app/login/page.tsx
src/app/map/page.tsx
src/app/mypage/page.tsx
src/app/page.tsx
src/app/search/page.tsx
src/components/Header.tsx
src/components/information/InformationFrame.tsx
src/components/main/CardSection/CalculateCard.tsx
src/components/main/CardSection/NewsCard.tsx
src/components/main/CardSection/PopularCard.tsx
src/components/main/FilterSection/FilterSection.tsx
src/components/main/FilterSection/RadioButton.tsx
src/components/policyDetail/business/BusinessPay.tsx
src/components/policyDetail/policy/PolicyReform.tsx

- 크로스 브라우징 CSS 에러 해결
- 모바일 css interaction 해결
- 모바일 dialog 버튼 클릭시 close 및 Transition 추가
- 가장 작은 모바일 화면에 맞춰 반응형 css 수정
---
- 사파리에서는 적용되지 않던 css를 제거하여 해결 (height을 지정 시 크롬에서는 flex-wrap 되지만 사파리에서는 적용되지 않음)
- 모바일에서는 hover interaction에 delay가 있어 interaction 제거
- 모바일 메뉴 Dialog 버튼 클릭시 dialog close 되도록 변경
- Dialog에 Transition 적용
---
---
- 내용을 입력해주세요

[FIX] 크로스 브라우징 CSS 에러 해결

---

src/components/detail/DetailFrame.tsx
src/components/detail/KakaoMap.tsx

- 좋아요 버튼 스크랩으로 변경했습니다
-  전화번호는 모바일 시 hidden으로 변경했습니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Chore] css 수정

---

src/components/commonSearch/SearchCard.tsx
src/components/main/CardSection/PopularCard.tsx
src/components/main/SearchSection/SearchSection.tsx
src/components/mainSearch/MainSearchFrame.tsx
src/components/mapSearch/MapSearchFrame.tsx

- 인기 복지 클릭하면 상세 페이지로 이동되게 구현했습니다 목록 페이지에서 결과 없을 때 ui 구현했습니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[feat] 인기 복지 클릭 시 상세 페이지 이동 및 결과 없을 시 ui 구현 

---

src/components/commonSearch/DetailSearchFrame.tsx
src/components/commonSearch/SearchCard.tsx
src/components/filterSearch/FilterSearchFrame.tsx
src/components/main/FilterSection/FilterSection.tsx

- filter search api 구현했습니다 더불어 페이지네이션에서 결과가 없을 시 ui도 구현했습니다
---
- recoil 삭제 후 form의 event value를 받아서 routing하는 것으로 구현했습니다
---
---
- 내용을 입력해주세요

[Feat] filter search api 구현

---

src/components/commonSearch/DetailSearchFrame.tsx
src/components/filterSearch/FilterSearchFrame.tsx
src/components/main/FilterSection/RadioBox.tsx
src/components/mainSearch/MainSearchFrame.tsx

- rc-pagination 을 통해 pagination 구현
- pathname과 searchParams를 통해 router push 구현
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Feat] pagination 구현

---

src/app/oauth/kakao/page.tsx
src/components/Header.tsx
src/components/detail/DetailFrame.tsx
src/components/my/MypageFrame.tsx
src/state/index.ts

- localStorage -> Recoil 변경
- 로그인 실행 순서 제어 수정 
---
- localStorage에서 저장하던 kakaoToken을 Recoil KakaoToken Atom에 저장
- 카카오에서 토큰 받았을 때 Mutate를 실행하여 실행순서 제어
---
---
- 내용을 입력해주세요

[FIX] localStorage -> Recoil 변경 및 로그인 실행 순서 제어 수정 

---

src/components/detail/KakaoMap.tsx
src/components/login/LoginFrame.tsx
src/components/main/map/MapFrame.tsx

- kakao map url 수정했습니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Refactor] kakao map url 수정

---

src/components/Header.tsx

- ssr hydration 에러 해결  #50 
---
- useState로 hydrated라는 상태를 통해 useEffect 훅 호출 이전에는 스토어의 초기값을 반환하고, useEffect 훅 호출 이후에 recoil 스토어의 hydration을 실행시키는 역할을 담당한다.
- 즉, SSR의 결과값이 클라이언트에서 Hydration 된 후에 recoil-persist 스토어가 hydration 되는 것을 보장한다. 
- 이를 통해 Text content does not match server-rendered HTML가 발생하는 원인을 막을 수 있다.
---
---
- 내용을 입력해주세요

[FIX] ssr hydration 에러 해결

---

src/components/detail/DetailFrame.tsx

- 카카오맵 보이게 했습니다 하지만 간헐적으로 지도 대신 흰색 부분이 보이는 것에 대해 해결이 필요합니다 
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Fix] 카카오맵 에러 수정

---

src/app/layout.tsx
src/components/Header.tsx
src/components/detail/ContentCard.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/KakaoMap.tsx
src/state/index.ts

- 카카오맵 에러 해결
- atom Type 추가
- 상세페이지 데이터 Type 추가
---
- 맵 컴포넌트에 있던 API 스크립트를 최상단 Layout으로 이동
- atom state에 type을 추가
- 상세페이지 데이터를 IChildCareData와 IChildCenterData 인터페이스로 각각 선언 후 IDetailData로 합침
---
---
- 내용을 입력해주세요

[FIX] 카카오맵 에러 해결

---

src/app/(header)/about-us/page.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/KakaoMap.tsx

- 게시물 스크랩 구현
---
- postScrapMutate를 정의 후 button 눌렀을 때 onSubmit으로 로그인 여부 확인후 mutate
---
---
- 내용을 입력해주세요

[Feat] 게시물 스크랩 구현

---

src/components/my/MypageFrame.tsx
src/components/my/MypageReview.tsx

- 마이페이지 좋아요, 리뷰 조회 구현했습니다 현재 리뷰는 따로 컴포넌트 분리한 상태입니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Feat] 마이페이지 좋아요, 리뷰 조회 구현

---

src/components/detail/DetailFrame.tsx
src/components/detail/Review.tsx
src/components/searchList/FilterSearchFrame.tsx

- 필터 검색 쿼리 재호출 로직 추가
- 리뷰 CRUD 구현
---
- 필터 검색 시 캐싱된 data가 fetching되지 않아 검색 버튼 클릭 시 직접 fetch
- 로그인 했을 시에만 리뷰를 작성 또는 열람 가능하며 mutate를 통해 CRUD 구현
---
---
- 내용을 입력해주세요

[Feat] 리뷰 CRUD 구현

---

src/app/layout.tsx
src/components/my/MypageFrame.tsx
src/components/my/MypageReview.tsx

- recoil state -> recoil value
- layout bg color 및 h-screen 수정
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Refactor] css 수정 및 recoil state 수정

---

src/components/Logo.tsx
src/components/commonSearch/SearchCard.tsx
src/components/detail/ContentCard.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/KakaoMap.tsx
src/components/detail/Review.tsx
src/components/main/CardSection/NewsCard.tsx
src/components/main/FilterSection/FilterSection.tsx
src/components/main/FilterSection/RadioBox.tsx
src/components/my/MypageFrame.tsx
src/components/my/MypageReview.tsx

- 모바일 화면 크기에 맞게 반응형 수정
- sweetalert2로 alert 대체 및 구현
- 마이페이지 Type 추가
- 로고 크기 반응형 추가
- 마이페이지 스크랩 및 리뷰 텍스트 재구성
- 리뷰 작성자 확인 후 자기 댓글만 메뉴 뜨도록 수정
---
- 비회원 로그인 시 스크랩, 마이페이지 접근 시 alert 후 login 유도
- 로그아웃 시 alert
- 리뷰 작성자 isWriter 확인 후 자기 댓글만 메뉴가 생겨서 수정 및 삭제 가능하도록 구현
---
---
- 내용을 입력해주세요

[Chore] 반응형 스타일 수정 및 alert 구현

---

src/app/(header)/error/page.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/Review.tsx
src/components/my/MypageReview.tsx
src/components/searchList/FilterSearchFrame.tsx
src/components/searchList/MainSearchList.tsx
src/components/searchList/MapSearchList.tsx

- 에러 했을 때 return된 값들 모두 추가해줬습니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Refactor] 에러 처리

---

src/app/layout.tsx
src/components/commonSearch/DetailSearchFrame.tsx
src/components/commonSearch/SearchCard.tsx
src/components/commonSearch/SearchSkeleton.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/DetailSkeleton.tsx
src/components/detail/KakaoMap.tsx
src/components/detail/Review.tsx
src/components/login/LoginFrame.tsx
src/components/main/CardSection/NewsCard.tsx
src/components/main/CardSection/PopularCard.tsx
src/components/main/SearchSection/SearchSection.tsx
src/components/mainSearch/MainSearchFrame.tsx
src/components/mapSearch/MapSearchFrame.tsx
src/components/mapSearch/MapSearchSkeleton.tsx
src/components/my/MypageFrame.tsx
src/components/my/MypageReview.tsx
src/components/my/MypageSkeleton.tsx
src/components/searchList/FilterSearchFrame.tsx
src/components/searchList/FilterSearchSkeleton.tsx
src/components/searchList/MainSearchList.tsx
src/components/searchList/MapSearchList.tsx
src/components/searchList/SearchListSkeleton.tsx

- Skeleton 구현
- 각 페이지 데이터 Type 추가
- 에러 체크
- 네이버 로그인 삭제
---
- Skeleton 구현 후 isLoading시 대체 UI 보여줌
- Type 추가
---
---
- 내용을 입력해주세요

[Feat] Skeleton 구현 및 Type 에러 추가, 에러 체크

---

src/components/detail/DetailFrame.tsx
src/components/detail/KakaoMap.tsx

- 불필요한 렌더링 삭제
---
- null병합 연산자로 에러 처리 및 불필요한 사전 렌더링 제거
---
---
- 내용을 입력해주세요

hotfix: 카카오맵 에러 수정

---

src/app/NextProvider.tsx
src/app/layout.tsx
src/components/detail/DetailFrame.tsx
src/components/detail/DetailSkeleton.tsx
src/components/detail/KakaoMap.tsx

- 소셜로그인 시 리다이렉트로 인해 카카오맵 API Script가 날라감 #66 
---
- Injection Hook으로 매번 확인 후 Injection
---
---
- 내용을 입력해주세요

[FIX] 소셜로그인 시 카카오맵 API InJection

---

src/components/information/InformationFrame.tsx
src/components/main/FilterSection/FilterSection.tsx
src/components/policyDetail/business/BusinessCare.tsx
src/components/policyDetail/business/BusinessPay.tsx
src/components/policyDetail/childcare/CareWaitingAdmission.tsx
src/components/policyDetail/policy/PolicyCredit.tsx
src/components/policyDetail/policy/PolicyExpansion.tsx
src/components/policyDetail/policy/PolicyHistory.tsx
src/components/policyDetail/policy/PolicyStatus.tsx

- 실제 페이지와 정책명이 달라서 모두 수정하였습니다
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요

[Style] 정책명 수정

---

src/components/my/MypageFrame.tsx
src/components/my/MypageReview.tsx

- 마이페이지, 리뷰와 스크랩에서 truncate 적용 안됨 수정
---
- 부모 요소인 flex에도 truncate 추가 적용
---
---
- 내용을 입력해주세요

[FIX] truncate 적용 안됨 수정
